// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"time"
)

type Todo struct {
	ID        string
	Title     string
	Done      bool
	CreatedAt time.Time
}

type User struct {
	ID        string
	Email     string
	Password  string
	CreatedAt time.Time
}
