// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package sqlcgen

import (
	"context"
	"time"
)

const createUser = `-- name: CreateUser :exec
INSERT INTO users (id, email, password, created_at)
VALUES ($1, $2, $3, $4)
`

type CreateUserParams struct {
	ID        string
	Email     string
	Password  string
	CreatedAt time.Time
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.Password,
		arg.CreatedAt,
	)
	return err
}

const delete = `-- name: Delete :exec
DELETE FROM todos WHERE id = $1
`

func (q *Queries) Delete(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, delete, id)
	return err
}

const getAll = `-- name: GetAll :many
SELECT id, title, done, created_at FROM todos ORDER BY created_at DESC
`

func (q *Queries) GetAll(ctx context.Context) ([]Todo, error) {
	rows, err := q.db.QueryContext(ctx, getAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Todo
	for rows.Next() {
		var i Todo
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Done,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getByID = `-- name: GetByID :one
SELECT id, title, done, created_at FROM todos WHERE id = $1
`

func (q *Queries) GetByID(ctx context.Context, id string) (Todo, error) {
	row := q.db.QueryRowContext(ctx, getByID, id)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Done,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password, created_at FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.CreatedAt,
	)
	return i, err
}

const save = `-- name: Save :exec
INSERT INTO todos (id, title, done, created_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (id) DO UPDATE
SET title = EXCLUDED.title,
    done = EXCLUDED.done
`

type SaveParams struct {
	ID        string
	Title     string
	Done      bool
	CreatedAt time.Time
}

func (q *Queries) Save(ctx context.Context, arg SaveParams) error {
	_, err := q.db.ExecContext(ctx, save,
		arg.ID,
		arg.Title,
		arg.Done,
		arg.CreatedAt,
	)
	return err
}
